# Database access — TTC GTFS-RT (VehiclePositions)

The Postgres/PostGIS container is published on **host port 5433** → container port 5432.

| setting  | value          |
|----------|----------------|
| host     | `localhost`    |
| port     | `5433`         |
| user     | `ttc`          |
| password | `ttc`          |
| database | `ttc_gtfsrt`   |

**URL forms**

- from a notebook / host shell: `postgresql+psycopg://ttc:ttc@localhost:5433/ttc_gtfsrt`
- from another compose service (api, collector, dashboard): `postgresql+psycopg://ttc:ttc@postgres:5432/ttc_gtfsrt`
- raw psql inside the container: `docker compose exec postgres psql -U ttc -d ttc_gtfsrt`

Tables in the current schema:

- `feed_fetch_logs` — one row per fetch attempt (success or failure)
- `raw_gtfsrt_snapshots` — raw protobuf bytes (one per successful fetch)
- `vehicle_positions` — normalized per-entity rows; includes `geom GEOMETRY(Point, 4326)` (PostGIS, generated from lon/lat)

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg://ttc:ttc@localhost:5433/ttc_gtfsrt")

### Recovering from a `PendingRollbackError`

If a previous query errored, the engine's pooled connection will refuse new work until the aborted transaction is rolled back. Dispose the engine and rebuild:

In [2]:
engine.dispose()
engine = create_engine("postgresql+psycopg://ttc:ttc@localhost:5433/ttc_gtfsrt")

## Schema overview

In [3]:
pd.read_sql("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    ORDER BY table_name
""", engine)

             table_name
0       alembic_version
1        analytics_runs
2       feed_fetch_logs
3     geography_columns
4      geometry_columns
5  raw_gtfsrt_snapshots
6       spatial_ref_sys
7     trip_trajectories
8     vehicle_positions

In [4]:
pd.read_sql("""
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'vehicle_positions'
    ORDER BY ordinal_position
""", engine)

              column_name                 data_type
0                      id                    bigint
1             snapshot_id                    bigint
2              fetched_at  timestamp with time zone
3   feed_header_timestamp  timestamp with time zone
4               entity_id         character varying
5       vehicle_timestamp  timestamp with time zone
6              vehicle_id         character varying
7           vehicle_label         character varying
8                 trip_id         character varying
9                route_id         character varying
10           direction_id                  smallint
11             start_date         character varying
12             start_time         character varying
13  schedule_relationship         character varying
14               latitude          double precision
15              longitude          double precision
16                bearing          double precision
17               odometer          double precision
18              speed_mps          double precision
19         current_status         character varying
20  current_stop_sequence                   integer
21                stop_id         character varying
22       occupancy_status         character varying
23   occupancy_percentage                  smallint
24       congestion_level         character varying
25             raw_entity                     jsonb
26                   geom              USER-DEFINED

## Common queries

In [5]:
# Recent fetch attempts (success + failure)
pd.read_sql("""
    SELECT fetched_at, success, http_status, duration_ms, entity_count,
           error_type, error_message
    FROM feed_fetch_logs
    ORDER BY fetched_at DESC
    LIMIT 10
""", engine)

,fetched_at,success,http_status,duration_ms,entity_count,error_type,error_message
0,2026-04-22 03:50:26.900530+00:00,True,200,41,1149,None,None
1,2026-04-22 03:50:06.879843+00:00,True,200,44,1149,None,None
2,2026-04-22 03:49:46.859558+00:00,True,200,41,1149,None,None
3,2026-04-22 03:49:26.927653+00:00,True,200,39,1152,None,None
4,2026-04-22 03:49:06.915897+00:00,True,200,41,1152,None,None
5,2026-04-22 03:48:46.961710+00:00,True,200,46,1152,None,None
6,2026-04-22 03:48:26.953896+00:00,True,200,40,1160,None,None
7,2026-04-22 03:48:06.944498+00:00,True,200,43,1160,None,None
8,2026-04-22 03:47:47.005811+00:00,True,200,42,1159,None,None
9,2026-04-22 03:47:27.008837+00:00,True,200,40,1160,None,None

In [6]:
# Latest observation per vehicle (the "hot" query — indexed on (vehicle_id, fetched_at DESC))
pd.read_sql("""
    SELECT DISTINCT ON (vehicle_id)
           vehicle_id, route_id, trip_id, latitude, longitude,
           speed_mps, bearing, current_status, occupancy_status, fetched_at
    FROM vehicle_positions
    WHERE vehicle_id IS NOT NULL
      AND fetched_at > now() - interval '5 minutes'
    ORDER BY vehicle_id, fetched_at DESC
    LIMIT 50
""", engine)

,vehicle_id,route_id,trip_id,latitude,longitude,speed_mps,bearing,current_status,occupancy_status,fetched_at
0,1,None,None,43.658516,-79.325241,0.000000,282.0,None,None,2026-04-22 03:50:26.900530+00:00
1,1219,None,None,43.693382,-79.494377,0.000000,357.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
2,1232,86,80853020,43.742039,-79.223755,13.411200,73.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
3,1236,130,99025020,43.810074,-79.257950,0.000000,165.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
4,1255,None,None,43.794964,-79.243965,0.000000,252.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
5,1259,86,60995020,43.732414,-79.263123,0.000000,238.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
6,1272,134,25595020,43.781654,-79.234802,8.046720,255.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
7,1274,116,79085020,43.752571,-79.180740,12.070080,230.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
8,1277,116,20936020,43.794357,-79.196350,13.858240,0.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
9,1281,27,125927020,43.683792,-79.498779,8.940800,158.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
10,1310,None,None,43.693367,-79.494263,0.000000,351.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
11,1315,805,93066020,43.711117,-79.377022,0.000000,255.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
12,1321,805,115277020,43.695930,-79.449196,10.728960,71.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
13,1323,41,1818020,43.770035,-79.502121,6.705600,66.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
14,1325,None,None,43.692356,-79.494759,0.000000,101.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
15,1327,71,21913020,43.670429,-79.485764,0.000000,252.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
16,1328,805,54577020,43.705597,-79.399811,0.894080,261.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
17,1331,29,25203020,43.710484,-79.453835,0.000000,352.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
18,1333,46,13069020,43.713428,-79.580688,0.000000,341.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
19,1334,None,None,43.692684,-79.495186,0.000000,206.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
20,1342,171,76554020,43.687103,-79.489609,0.894080,264.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
21,1353,35,78017020,43.776592,-79.508614,0.000000,319.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
22,1357,32,5782020,43.664154,-79.589844,10.728960,224.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
23,1358,161,96136020,43.684467,-79.450371,10.728960,255.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
24,1361,None,None,43.693516,-79.494102,0.000000,249.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
25,1382,158,68280020,43.700516,-79.517487,9.834880,291.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
26,1384,None,None,43.691673,-79.494957,0.000000,295.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
27,1386,506,106387020,43.667088,-79.404037,3.129280,348.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
28,1387,None,None,43.692493,-79.494736,0.000000,21.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
29,1399,35,77342020,43.761654,-79.518608,0.447040,351.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
30,1406,102,117268020,43.719563,-79.247398,11.623040,253.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
31,1407,95,80093020,43.785522,-79.193130,0.000000,255.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
32,1409,45,2942020,43.730034,-79.575401,10.728960,340.0,IN_TRANSIT_TO,FEW_SEATS_AVAILABLE,2026-04-22 03:50:26.900530+00:00
33,1412,102,70987020,43.727932,-79.229164,12.517119,39.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
34,1503,95,24400020,43.755119,-79.349457,13.411200,73.0,INCOMING_AT,FULL,2026-04-22 03:50:26.900530+00:00
35,1529,None,None,43.793568,-79.243408,0.000000,161.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
36,1532,85,1773020,43.784973,-79.281021,11.623040,254.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
37,1534,None,None,43.793674,-79.243439,0.000000,159.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
38,1536,116,75565020,43.819759,-79.223564,0.000000,111.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
39,1549,133,7005020,43.745762,-79.273552,11.176000,344.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
40,1553,None,None,43.795002,-79.243942,0.000000,237.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
41,1559,134,13840020,43.817032,-79.232117,0.000000,343.0,STOPPED_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
42,1560,36,91862020,43.780071,-79.414604,2.235200,344.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
43,1575,505,-1473799614,43.650635,-79.405273,0.000000,345.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
44,1595,102,57169020,43.774155,-79.231010,11.176000,164.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
45,1603,133,35625020,43.767128,-79.271065,11.623040,173.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
46,1625,84,69835020,43.748177,-79.482559,5.364480,349.0,IN_TRANSIT_TO,EMPTY,2026-04-22 03:50:26.900530+00:00
47,1653,185,122664020,43.771553,-79.364975,0.000000,82.0,INCOMING_AT,EMPTY,2026-04-22 03:50:26.900530+00:00
48,1655,510,-1219207236,43.664516,-79.402611,1.341120,344.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00
49,1656,None,None,43.794971,-79.243851,0.000000,240.0,None,EMPTY,2026-04-22 03:50:26.900530+00:00

In [7]:
# Active vehicle count per route (last 15 min)
pd.read_sql("""
    WITH latest AS (
      SELECT DISTINCT ON (vehicle_id)
             vehicle_id, route_id, speed_mps, fetched_at
      FROM vehicle_positions
      WHERE fetched_at > now() - interval '15 minutes'
        AND vehicle_id IS NOT NULL
      ORDER BY vehicle_id, fetched_at DESC
    )
    SELECT route_id,
           count(*)                           AS active_vehicles,
           avg(speed_mps) * 3.6               AS avg_speed_kph,
           max(fetched_at)                    AS latest_seen
    FROM latest
    WHERE route_id IS NOT NULL
    GROUP BY route_id
    ORDER BY active_vehicles DESC
    LIMIT 20
""", engine)

   route_id  active_vehicles  avg_speed_kph                      latest_seen
0       504               23      13.504495 2026-04-22 03:50:26.900530+00:00
1       501               23      12.454923 2026-04-22 03:50:26.900530+00:00
2       506               20      10.460736 2026-04-22 03:50:26.900530+00:00
3       505               20       5.954573 2026-04-22 03:50:26.900530+00:00
4        52               16      12.070080 2026-04-22 03:50:26.900530+00:00
5       102               16      23.737823 2026-04-22 03:50:26.900530+00:00
6        96               14      17.242971 2026-04-22 03:50:26.900530+00:00
7       510               14       2.184110 2026-04-22 03:50:26.900530+00:00
8        95               13      18.321762 2026-04-22 03:50:26.900530+00:00
9       805               13      18.321762 2026-04-22 03:50:26.900530+00:00
10      129               11      25.017984 2026-04-22 03:50:26.900530+00:00
11       39               11      18.434304 2026-04-22 03:50:26.900530+00:00
12       53               10      23.013618 2026-04-22 03:50:26.900530+00:00
13       54               10      19.312128 2026-04-22 03:50:26.900530+00:00
14       85               10      18.829324 2026-04-22 03:50:26.900530+00:00
15       86               10      18.829325 2026-04-22 03:50:26.900530+00:00
16      165               10      18.829324 2026-04-22 03:50:26.900530+00:00
17      503               10      11.104474 2026-04-22 03:50:26.900530+00:00
18       25               10      20.116800 2026-04-22 03:50:26.900530+00:00
19       29                9      13.590015 2026-04-22 03:50:26.900530+00:00

In [8]:
# Occupancy breakdown over the last hour
pd.read_sql("""
    SELECT coalesce(occupancy_status, 'UNKNOWN') AS occupancy_status,
           count(*)                              AS n
    FROM vehicle_positions
    WHERE fetched_at > now() - interval '1 hour'
    GROUP BY 1
    ORDER BY n DESC
""", engine)

      occupancy_status       n
0                EMPTY  211105
1  FEW_SEATS_AVAILABLE   11655
2              UNKNOWN    1446
3                 FULL     466

## PostGIS examples

`vehicle_positions.geom` is a generated `GEOMETRY(Point, 4326)` column populated from `longitude`/`latitude`, with a GiST index.

In [9]:
# Latest positions inside a downtown-Toronto bounding box
pd.read_sql("""
    SELECT vehicle_id, route_id, latitude, longitude, fetched_at
    FROM vehicle_positions
    WHERE fetched_at > now() - interval '5 minutes'
      AND geom && ST_MakeEnvelope(-79.42, 43.63, -79.35, 43.68, 4326)
    ORDER BY fetched_at DESC
    LIMIT 50
""", engine)

   vehicle_id route_id   latitude  longitude                       fetched_at
0        4507      504  43.644005 -79.402405 2026-04-22 03:50:26.900530+00:00
1        3422      510  43.667221 -79.403664 2026-04-22 03:50:26.900530+00:00
2        3437     None  43.646107 -79.393738 2026-04-22 03:50:26.900530+00:00
3        4524      511  43.636173 -79.410149 2026-04-22 03:50:26.900530+00:00
4        4525      504  43.652557 -79.363373 2026-04-22 03:50:26.900530+00:00
5        4526      505  43.666389 -79.353065 2026-04-22 03:50:26.900530+00:00
6        3450     None  43.646915 -79.394424 2026-04-22 03:50:26.900530+00:00
7        6715     None  43.650749 -79.405319 2026-04-22 03:50:26.900530+00:00
8        4538      501  43.656078 -79.364639 2026-04-22 03:50:26.900530+00:00
9        4539      501  43.659554 -79.365593 2026-04-22 03:50:26.900530+00:00
10       4550      509  43.636494 -79.397301 2026-04-22 03:50:26.900530+00:00
11       3454      510  43.658386 -79.400208 2026-04-22 03:50:26.900530+00:00
12       3233      503  43.649059 -79.378342 2026-04-22 03:50:26.900530+00:00
13       3232      510  43.667122 -79.403976 2026-04-22 03:50:26.900530+00:00
14       8918       25  43.677666 -79.358612 2026-04-22 03:50:26.900530+00:00
15       4570      509  43.635834 -79.398125 2026-04-22 03:50:26.900530+00:00
16       4567      511  43.666828 -79.411415 2026-04-22 03:50:26.900530+00:00
17       4583      501  43.644268 -79.418686 2026-04-22 03:50:26.900530+00:00
18       4577      505  43.656189 -79.381187 2026-04-22 03:50:26.900530+00:00
19       4596      509  43.640835 -79.377724 2026-04-22 03:50:26.900530+00:00
20       3268      510  43.657742 -79.399940 2026-04-22 03:50:26.900530+00:00
21       8501       75  43.644390 -79.369148 2026-04-22 03:50:26.900530+00:00
22       8511      121  43.665684 -79.354622 2026-04-22 03:50:26.900530+00:00
23       8753      504  43.677135 -79.358208 2026-04-22 03:50:26.900530+00:00
24       8527       65  43.673450 -79.369133 2026-04-22 03:50:26.900530+00:00
25       7213      506  43.665234 -79.354057 2026-04-22 03:50:26.900530+00:00
26       8788      503  43.648094 -79.383629 2026-04-22 03:50:26.900530+00:00
27       8543        8  43.676342 -79.359039 2026-04-22 03:50:26.900530+00:00
28       8552      121  43.646343 -79.377655 2026-04-22 03:50:26.900530+00:00
29       8549       94  43.665306 -79.383606 2026-04-22 03:50:26.900530+00:00
30       7217      506  43.658051 -79.399292 2026-04-22 03:50:26.900530+00:00
31       8324      127  43.667393 -79.404167 2026-04-22 03:50:26.900530+00:00
32       8331      503  43.648422 -79.383759 2026-04-22 03:50:26.900530+00:00
33       7245      506  43.667187 -79.404076 2026-04-22 03:50:26.900530+00:00
34       8341     None  43.647961 -79.400253 2026-04-22 03:50:26.900530+00:00
35       8362       26  43.672905 -79.415474 2026-04-22 03:50:26.900530+00:00
36       8146      503  43.648716 -79.380005 2026-04-22 03:50:26.900530+00:00
37       8395       63  43.642071 -79.415253 2026-04-22 03:50:26.900530+00:00
38       9014        7  43.666061 -79.411064 2026-04-22 03:50:26.900530+00:00
39       7079       97  43.660400 -79.382706 2026-04-22 03:50:26.900530+00:00
40       8172     None  43.647686 -79.401604 2026-04-22 03:50:26.900530+00:00
41       3516       13  43.660587 -79.390793 2026-04-22 03:50:26.900530+00:00
42       4607      505  43.677013 -79.358147 2026-04-22 03:50:26.900530+00:00
43       4608      504  43.651646 -79.366165 2026-04-22 03:50:26.900530+00:00
44       1575      505  43.650635 -79.405273 2026-04-22 03:50:26.900530+00:00
45       4604      506  43.653095 -79.398109 2026-04-22 03:50:26.900530+00:00
46       4605      511  43.665894 -79.411415 2026-04-22 03:50:26.900530+00:00
47       4619      506  43.654903 -79.415817 2026-04-22 03:50:26.900530+00:00
48       4624      505  43.677048 -79.358315 2026-04-22 03:50:26.900530+00:00
49       3539     None  43.652805 -79.398201 2026-04-22 03:50:26.900530+00:00

In [10]:
# Vehicles currently within 500 m of Union Station (43.6453, -79.3806)
pd.read_sql("""
    SELECT DISTINCT ON (vehicle_id)
           vehicle_id, route_id,
           ST_DistanceSphere(geom, ST_SetSRID(ST_MakePoint(-79.3806, 43.6453), 4326)) AS meters,
           fetched_at
    FROM vehicle_positions
    WHERE fetched_at > now() - interval '5 minutes'
      AND ST_DWithin(geom::geography,
                     ST_SetSRID(ST_MakePoint(-79.3806, 43.6453), 4326)::geography,
                     500)
    ORDER BY vehicle_id, fetched_at DESC
""", engine)

   vehicle_id route_id      meters                       fetched_at
0        3233      503  455.800732 2026-04-22 03:50:26.900530+00:00
1        4596      509  481.489370 2026-04-22 03:49:26.927653+00:00
2        4627      504  369.237025 2026-04-22 03:50:26.900530+00:00
3        4649      504  459.096329 2026-04-22 03:45:47.171453+00:00
4        8146      503  382.845698 2026-04-22 03:50:26.900530+00:00
5        8331      503  430.256220 2026-04-22 03:50:26.900530+00:00
6        8437       19  199.677339 2026-04-22 03:50:26.900530+00:00
7        8477      114  346.421932 2026-04-22 03:50:26.900530+00:00
8        8552      121  263.831574 2026-04-22 03:50:26.900530+00:00
9        8788      503  394.875341 2026-04-22 03:50:26.900530+00:00
10       8819      503  497.355503 2026-04-22 03:45:47.171453+00:00

In [17]:
pd.read_sql("SELECT count(*) AS total_rows FROM trip_trajectories", engine)

   total_rows
0       78235

## Raw protobuf replay

`raw_gtfsrt_snapshots.payload` stores the exact bytes returned by the feed — useful for re-parsing or diagnostics.

In [11]:
from google.transit import gtfs_realtime_pb2

row = pd.read_sql(
    "SELECT payload FROM raw_gtfsrt_snapshots ORDER BY id DESC LIMIT 1", engine
)
payload_bytes = bytes(row["payload"].iloc[0])

msg = gtfs_realtime_pb2.FeedMessage()
msg.ParseFromString(payload_bytes)
print(f"entities: {len(msg.entity)}  header ts: {msg.header.timestamp}")
print(msg.entity[0])

entities: 1149  header ts: 1776829799
id: "1"
vehicle {
  trip {
    trip_id: "19649020"
    schedule_relationship: SCHEDULED
    route_id: "927"
  }
  position {
    latitude: 43.7440262
    longitude: -79.5950775
    bearing: 341
    speed: 0
  }
  current_stop_sequence: 15
  current_status: STOPPED_AT
  timestamp: 1776829783
  stop_id: "9760"
  vehicle {
    id: "3640"
  }
  occupancy_status: EMPTY
}